version: '3.7'
services:
  fms-c:
    image: centos-fms-c-19_2:latest
    container_name: fms-c
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - ./databases/:/opt/FileMaker/FileMaker Server/Data/Databases/
      - data-admin-conf:/opt/FileMaker/FileMaker Server/Admin/conf:delegated
      - data-conf:/opt/FileMaker/FileMaker Server/conf:delegated
      - data-data-backups:/opt/FileMaker/FileMaker Server/Data/Backups/:delegated
      - data-data-databases:/opt/FileMaker/FileMaker Server/Data/Databases/:delegated
      - data-data-preferences:/opt/FileMaker/FileMaker Server/Data/Preferences/:delegated
      - data-dbserver-extensions:/opt/FileMaker/FileMaker Server/Database Server/Extensions/:delegated
      - data-http-dotconf:/opt/FileMaker/FileMaker Server/HTTPServer/.conf:delegated
      - data-http-conf:/opt/FileMaker/FileMaker Server/HTTPServer/conf:delegated
      - data-http-logs:/opt/FileMaker/FileMaker Server/HTTPServer/logs:delegated
      - data-logs:/opt/FileMaker/FileMaker Server/Logs:delegated
      - data-webpub-conf:/opt/FileMaker/FileMaker Server/Web Publishing/conf:delegated
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    user: root
    environment:
      - container=docker
    cap_add:
      - SYS_ADMIN
    ports:
      - 80:80
      - 443:443
      - 2399:2399
      - 5003:5003
      - 16000-16002:16000-16002
    networks:
      fms:
        ipv4_address: 172.20.0.11
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "5"
    # init: true
    # privileged: true
    stop_signal: SIGRTMIN+3
    stop_grace_period: 20m
    restart: "no"
    stdin_open: true
    tty: true
    # command: bash

  fms:
    image: centos-fms-19_2:latest
    container_name: fms
    hostname: fms
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - data-admin-conf:/opt/FileMaker/FileMaker Server/Admin/conf:delegated
      - data-conf:/opt/FileMaker/FileMaker Server/conf:delegated
      - data-data-backups:/opt/FileMaker/FileMaker Server/Data/Backups/:delegated
      - data-data-databases:/opt/FileMaker/FileMaker Server/Data/Databases/:delegated
      - data-data-preferences:/opt/FileMaker/FileMaker Server/Data/Preferences/:delegated
      - data-dbserver-extensions:/opt/FileMaker/FileMaker Server/Database Server/Extensions/:delegated
      - data-http-dotconf:/opt/FileMaker/FileMaker Server/HTTPServer/.conf:delegated
      - data-http-conf:/opt/FileMaker/FileMaker Server/HTTPServer/conf:delegated
      - data-http-logs:/opt/FileMaker/FileMaker Server/HTTPServer/logs:delegated
      - data-logs:/opt/FileMaker/FileMaker Server/Logs:delegated
      - data-webpub-conf:/opt/FileMaker/FileMaker Server/Web Publishing/conf:delegated
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    user: root
    environment:
      - container=docker
    cap_add:
      - SYS_ADMIN
    ports:
      - 80:80
      - 443:443
      - 2399:2399
      - 5003:5003
      - 16000-16002:16000-16002
    networks:
      fms:
        ipv4_address: 172.20.0.11
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "5"
    # init: true
    # privileged: true
    stop_signal: SIGRTMIN+3
    stop_grace_period: 20m
    restart: "no"
    stdin_open: true
    tty: true
    # command: /usr/sbin/init

  d-fms2.fmgarage.com:
    # reverse proxy test
    image: centos-fms-19_2:2021-03-25
    container_name: fms2
    hostname: d-fms2.fmgarage.com
    depends_on:
      - reverse
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - ./data/:/opt/FileMaker/FileMaker Server/Data/Databases/
      # - ./build/:/root/build/
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    user: root
    environment:
      - container=docker
    cap_add:
      - SYS_ADMIN
    # ports:
    #   - 80:80
    #   - 443:443
    #   - 2399:2399
    #   - 5003:5003
    #   - 16000-16002:16000-16002
    networks:
      fms:
        ipv4_address: 172.20.0.12
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "5"
    # init: true
    # privileged: true
    stop_signal: SIGRTMIN+3
    restart: "no"
    stdin_open: true
    tty: true
    # command: bash

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 5003:5003
      - 16000:16000
    networks:
      fms:
        ipv4_address: 172.20.0.50
    volumes:
      - ./nginx_config:/etc/nginx
      - ./nginx_cert/:/etc/ssl/fmg/
    # command: bash

networks:
    fms:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.20.0.0/16

volumes:
#  tmpvolume:
#    external: true
  data-admin-conf:
    external: true
  data-dbserver-extensions:
    external: true
  data-data-backups:
    external: true
  data-data-databases:
    external: true
  data-data-preferences:
    external: true
  data-conf:
    external: true
  data-http-dotconf:
    external: true
  data-http-conf:
    external: true
  data-http-logs:
    external: true
  data-logs:
    external: true
  data-webpub-conf:
    external: true
