version: '3.9'
services:

  fms:
    image: centos-fms-19_2:latest
    container_name: fms-${ID}
    hostname: fms
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - fms-admin-conf:/opt/FileMaker/FileMaker Server/Admin/conf:delegated
      - fms-conf:/opt/FileMaker/FileMaker Server/conf:delegated
      - fms-data-backups:/opt/FileMaker/FileMaker Server/Data/Backups/:delegated
      - fms-data-databases:/opt/FileMaker/FileMaker Server/Data/Databases/:delegated
      - fms-data-preferences:/opt/FileMaker/FileMaker Server/Data/Preferences/:delegated
      - fms-data-scripts:/opt/FileMaker/FileMaker Server/Data/Scripts/:delegated
      - fms-dbserver-extensions:/opt/FileMaker/FileMaker Server/Database Server/Extensions/:delegated
      - fms-http-dotconf:/opt/FileMaker/FileMaker Server/HTTPServer/.conf:delegated
      - fms-http-conf:/opt/FileMaker/FileMaker Server/HTTPServer/conf:delegated
      - fms-http-logs:/opt/FileMaker/FileMaker Server/HTTPServer/logs:delegated
      - fms-logs:/opt/FileMaker/FileMaker Server/Logs:delegated
      - fms-webpub-conf:/opt/FileMaker/FileMaker Server/Web Publishing/conf:delegated
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    user: root
    environment:
      - container=docker
    cap_add:
      - SYS_ADMIN
#      - SYS_PTRACE # only for debugging!
    ports:
      - 80:80
      - 443:443
      - 2399:2399
      - 5003:5003
      - 16000-16002:16000-16002
    networks:
      fms:
        ipv4_address: 172.20.0.11
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "5"
    # init: true
    # privileged: true
    stop_signal: SIGRTMIN+3
    stop_grace_period: 10m
    restart: "no"
    stdin_open: true
    tty: true
    # command: /usr/sbin/init

networks:
  fms:
    external:
      name: fms-net

volumes:
  fms-admin-conf:
    name: fms-admin-conf-${ID}
    external: true
  fms-dbserver-extensions:
    name: fms-dbserver-extensions-${ID}
    external: true
  fms-data-backups:
    name: fms-data-backups-${ID}
    external: true
  fms-data-databases:
    name: fms-data-databases-${ID}
    external: true
  fms-data-preferences:
    name: fms-data-preferences-${ID}
    external: true
  fms-data-scripts:
    name: fms-data-scripts-${ID}
    external: true
  fms-conf:
    name: fms-conf-${ID}
    external: true
  fms-http-dotconf:
    name: fms-http-dotconf-${ID}
    external: true
  fms-http-conf:
    name: fms-http-conf-${ID}
    external: true
  fms-http-logs:
    name: fms-http-logs-${ID}
    external: true
  fms-logs:
    name: fms-logs-${ID}
    external: true
  fms-webpub-conf:
    name: fms-webpub-conf-${ID}
    external: true
